### ISSUE TITLE
Add about page

### ISSUE THREAD

**Issue by michel-kraemer** [vert-x3/web-site#13]
Include core team and contributors.

* Avatar
* Twitter handle (if available)
* GitHub account
* Website (if available)
* Role in the team (if applicable)

**Comment by michel-kraemer** [comment]
For the time being we will include the core developers (Tim and Julien) and myself as a contributor for web design. A complete list of contributors is currently being compiled by Tim: https://groups.google.com/forum/#!topic/vertx/p2TejXDhOyg

**Comment by michel-kraemer** [comment]
In response to issue #8 I propose the following structure for the 'about' page (maybe 'community' page):

```
-----------------------------------------------------------------
Core Team:                       |   Get help:
                                 |   - Google User Group
Tim     Julien                   |   - Google Dev Group
                                 |
Contributors:                    |   How to contribute:
                                 |   There are many possibilities to
Name1   Name2   Name3            |   help. Lorem ipsum ....
                                 |
Name4  Name5    Name6            |   Keep up to date
                                 |   - Talks/Slides
....                             |   - Videos
                                 |   ....
-----------------------------------------------------------------
```

In other words: the list of contributors goes to the left and any information about the community and anything else related to that goes to the right. Of course it would be up to @purplefox and @vietj to fill the right side with content. WDYT?

Cheers,
Michel

**Comment by purplefox** [comment]
Looks good.
