### ISSUE TITLE
Add JAX innovation award image

### ISSUE THREAD

**Issue by michel-kraemer** [vert-x3/web-site#16]
And could we also add the JAX innovation award image somewhere too? :) (the one on the vertx.io website)

**Comment by michel-kraemer** [comment]
@purplefox The award is almost a year old. JAX 2015 will take place in two or three weeks. Should we add the award image to the front page or maybe to the new about page or somewhere else?

**Comment by purplefox** [comment]
Yeah, probably we should put this on a different page.

**Comment by michel-kraemer** [comment]
The new community page could be a good place (see #13).
