### ISSUE TITLE
Logos in white?

### ISSUE THREAD

**Issue by michel-kraemer** [vert-x3/web-site#19]
The initial idea was to have only monochrome (i.e. white) logos in the 'Who is using Vert.x' section. Any objections?

**Comment by purplefox** [comment]
+1

**Comment by michel-kraemer** [comment]
Changes can be previewed here: http://vert-x3-preview.michel-kraemer.com/

**Comment by purplefox** [comment]
Michel - I have a bunch more logos to convert to monochrome.

If you can tell me how to do it (Don't have photoshop but do have Gimp) I can do the rest myself so as not to bother you each time :)

**Comment by michel-kraemer** [comment]
Increase brightness to 100% and decrease saturation to 0%. The RedHat logo needed some extra work because not all elements could be differentiated well in monochrome. So if you don't get good results, send me the logo(s).

If you add the images to the webpage, please follow these 'guidelines':
* make them 180px wide (see the other logos already there)
* set correct width and height in the HTML file to avoid stretching the images
* if the logo seems too large (i.e. too dominant compared to the others) add a small transparent border to the left and right in Gimp but keep the 180px. (see `jClarity_logo.png` for example).

By the way, it's much fun for me working on the website. You may send me as many logos as you like :-)

Hope this helps,
Michel

**Comment by michel-kraemer** [comment]
Oh, and I sorted the logos alphabetically by the way.

**Comment by purplefox** [comment]
I tried to edit some logos myself in GIMP but couldn't get them right, so If you could do it, it would be a great help :)

**Comment by michel-kraemer** [comment]
Sure thing. I received two logos by mail. You can send me the others as well if you like.

By the way: I still don't have the right permissions to commit to this repository. I'm wondering if I should send you a PR for such small changes. I don't want to keep you away from more important work. :-)

**Comment by purplefox** [comment]
I messed up the teams, but you should be ok to push now :)

**Comment by michel-kraemer** [comment]
Works perfectly. I just pushed my first commit! :-) I moved the `highlight.pack.js` file to the correct location to fix the syntax highlighting.

**Comment by michel-kraemer** [comment]
I just added new logos of Bosh, Cyanogen and Groupon.
