### ISSUE TITLE
Docs menu layout bug with Safari

### ISSUE THREAD

**Issue by vietj** [vert-x3/web-site#29]
buggy display after scrolling a bit vertically

![screen shot 2015-04-21 at 14 13 33](https://cloud.githubusercontent.com/assets/225674/7252103/f2f67c26-e831-11e4-8bb0-05dc1423c003.png)

**Comment by michel-kraemer** [comment]
PR #30 should fix this. Can you please test and submit perhaps?

I deployed the fix here:
http://vert-x3-preview.michel-kraemer.com/docs/vertx-core/java/

Cheers,
Michel

**Comment by vietj** [comment]
it works now.

**Comment by michel-kraemer** [comment]
Great! I suppose you will submit the PR yourself or should we wait for Tim? Or should I do it myself? (sorry for my ignorance, I'm still new to your development process)
