### ISSUE TITLE
Docker images

### ISSUE THREAD

**Issue by vietj** [vert-x3/web-site#51]
@michel-kraemer we need to integrate in the web-site with Docker infos:

- docker registry with Vert.x images : https://registry.hub.docker.com/repos/vertx/
- docker examples
    - https://github.com/vert-x3/vertx-stack/tree/master/docker/vertx-docker-example
    - https://github.com/vert-x3/vertx-stack/tree/master/docker/vertx-docker-example-fabric8

@cescoffier can help to provide the appropriate wording, etc...

**Comment by michel-kraemer** [comment]
Sure thing.

@cescoffier I suppose you want to add the links here?
http://vert-x3.github.io/docs/

Michel

**Comment by cescoffier** [comment]
Exactly.

We don't have a _manual_ right now. I should create one. Anyway, here are the important links:

* Vert.x Docker Image: https://registry.hub.docker.com/repos/vertx/
* Examples (and source): https://github.com/vert-x3/vertx-stack/tree/master/docker

Is this ok ? 

New examples are landing soon.

**Comment by michel-kraemer** [comment]
OK. I will add them later today (after I return from work). I can include any information that you can send me until then.

**Comment by cescoffier** [comment]
For now, there is not much to add. Just the links would be enough. For the final version, we would have a proper manual.

**Comment by michel-kraemer** [comment]
See #53. Maybe you can ask Tim or Julien to get permissions to submit this PR.

**Comment by cescoffier** [comment]
To _merge_ you mean ?

**Comment by michel-kraemer** [comment]
Indeed :-)
