### ISSUE TITLE
Change logo href to not point to index.html

### ISSUE THREAD

**Issue by newoga** [vert-x3/web-site#6]
We should just be able to point it to base with something like:

``` html
<a href="" class="navbar-bran"d>
    <img alt="Brand" src="assets/logo-sm.png">
</a>
```

That way when you click on the link, it won't show `index.html` in the address bar.

**Comment by michel-kraemer** [comment]
See my comment in #9. Refers to #24.

**Comment by michel-kraemer** [comment]
#24 has been merged. This also solves this issue.

@newoga, thanks for your contribution anyhow.
