### ISSUE TITLE
proposal: Community page instead of dropdown

### ISSUE THREAD

**Issue by newoga** [vert-x3/web-site#8]
I'm open to debating this, but how about having a page for Community instead of the dropdown that points to the two google groups?

I think we get the following benefits from that change:
1. We have another opportunity to reiterate where to look for certain type of information or what types of questions issues should be posted where.
2. We could remove the wiki link from the navbar which feels out of place and put it on the community page.
3. We have a page where we can expand in the event we add tutorials or training or other places for good information.

I also find that drop downs on webpages are a little less friendly on mobile devices, even with responsive support.

Examples: 
Arangodb: https://www.arangodb.com/community
Play framework: https://www.playframework.com/get-involved
node.js: https://nodejs.org/community/
mongodb: https://www.mongodb.org/get-involved

**Comment by michel-kraemer** [comment]
Great idea. I guess we can combine this with the planned about page. Please see #13.

**Comment by purplefox** [comment]
+1

**Comment by purplefox** [comment]
I was thinking it would be also great to have a "community news" section (or new page) - this is where the greater vert.x community could have entries posted, e.g. maybe there is a Vert.x user group starting somewhere, or a user has created a new service that they want to announce. So basically a place for the community to be able to announce and publicise stuff that's not necessarily about vert.x core or official services.

**Comment by michel-kraemer** [comment]
Something like a blog maybe? Or a forum?

We have a static site of course, so we need some kind of an external service (something similar to Disqus) to allow others to post things. Or they need to send us pull requests. Any other idea?

**Comment by purplefox** [comment]
Actually, it would be great to have a blog attached, but that is a different discussion :)

I was thinking for the community page maybe just a static page, where we can maintain links to vert.x related community projects and events.

**Comment by newoga** [comment]
A page for news where people can share things like projects and events would be cool. 

As an alternative, we may be able to borrow one or some of these approaches that I've seen in the angular.js community:
1. Twitter account retweets events, blog posts, projects that would be helpful to the greater community. (I've notice we have a twitter account already, maybe put a twitter stream on the website/community page to encourage vert.x developers to follow that for updates to good content?) ex. https://twitter.com/angularjs
2. Google+ community where people can also make posts and projects or tools they've written or worked on, also raise questions or issues they're running into, (this probably has too much overlap with our current vertx google group, but is technically still an option) ex. https://plus.google.com/communities/115368820700870330756
3. Blog that has content that is written from vert.x core developers. In the angular community, the content here is usually longer and is typically vision oriented, ie where the project is going, big updates, change management related things...ex. http://angularjs.blogspot.com/

Overall, I like reusing existing popular channels/social networks that developers are already accustomed to following such as Github,Twitter, Google Groups, G+, etc. Lots of time that way we get mobile and notification support out of the box and we don't have to worry about content getting stale making sure we keep the website updated and fresh. I also think it's good to  use the website as a means to reinforce/draw people to those areas rather than add an additional place for them to look.

**Comment by newoga** [comment]
Another approach for listing related community projects is to create a curated list of them as a github repo.

examples: https://github.com/avelino/awesome-go, https://github.com/vinta/awesome-python

We could highlight a repository like that on the community page, and it'd also have the benefit of having visibility on github.

Sorry, I'm just brain dumping things I've seen that I thought have been helpful. Not necessarily saying we should do any or all, just thought I'd throw these options out there for consideration.

**Comment by michel-kraemer** [comment]
+1 for something like awesome-go on GitHub.

**Comment by purplefox** [comment]
+1 for awesome-vertx. I'll start a new issue for that as the original issue here was about a community page which we now have anyway :)
